<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoStdLib>true</NoStdLib>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>DariusPrototype</AssemblyName>
    <GameDir>..\..</GameDir>
    <GameManagedDir>$(GameDir)\Shape of Dreams_Data\Managed</GameManagedDir>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\TravelerBasicAttackVfxReplication.cs" Link="TravelerBasicAttackVfxReplication.cs" />
    <Reference Include="mscorlib"><HintPath>$(GameManagedDir)\mscorlib.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="netstandard"><HintPath>$(GameManagedDir)\netstandard.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="System"><HintPath>$(GameManagedDir)\System.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="System.Core"><HintPath>$(GameManagedDir)\System.Core.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(GameManagedDir)\0Harmony.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>$(GameManagedDir)\Assembly-CSharp.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="Dew.Core"><HintPath>$(GameManagedDir)\Dew.Core.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="Dew.Contents"><HintPath>$(GameManagedDir)\Dew.Contents.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="Dew.External"><HintPath>$(GameManagedDir)\Dew.External.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="Dew.UI"><HintPath>$(GameManagedDir)\Dew.UI.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="Mirror"><HintPath>$(GameManagedDir)\Mirror.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="Newtonsoft.Json"><HintPath>$(GameManagedDir)\Newtonsoft.Json.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="Sirenix.Serialization"><HintPath>$(GameManagedDir)\Sirenix.Serialization.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(GameManagedDir)\UnityEngine.CoreModule.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.UI"><HintPath>$(GameManagedDir)\UnityEngine.UI.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>$(GameManagedDir)\UnityEngine.IMGUIModule.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.ParticleSystemModule"><HintPath>$(GameManagedDir)\UnityEngine.ParticleSystemModule.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>$(GameManagedDir)\UnityEngine.PhysicsModule.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.InputLegacyModule"><HintPath>$(GameManagedDir)\UnityEngine.InputLegacyModule.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.ImageConversionModule"><HintPath>$(GameManagedDir)\UnityEngine.ImageConversionModule.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.AudioModule"><HintPath>$(GameManagedDir)\UnityEngine.AudioModule.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule"><HintPath>$(GameManagedDir)\UnityEngine.UnityWebRequestModule.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.UnityWebRequestAudioModule"><HintPath>$(GameManagedDir)\UnityEngine.UnityWebRequestAudioModule.dll</HintPath><Private>False</Private></Reference>
    <Reference Include="UnityEngine.AnimationModule"><HintPath>$(GameManagedDir)\UnityEngine.AnimationModule.dll</HintPath><Private>False</Private></Reference>
  </ItemGroup>
</Project>
